# Generated by Django 5.2.3 on 2025-06-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('machine_location', models.CharField(max_length=100)),
                ('machine_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100, unique=True)),
                ('sensor_description', models.TextField()),
                ('sensor_type', models.CharField(choices=[('progress', 'Progress'), ('min_max', 'Min/Max'), ('speedometer', 'Speedometer'), ('error_treshold', 'Error Treshold'), ('no_vis', 'No Visualisation')], default='no_vis', max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_value', models.FloatField()),
                ('unit', models.CharField(default='Milimeters', max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='machines.machine')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('machine', 'timestamp')},
            },
        ),
    ]
